/* eslint-disable prettier/prettier */
import { Book } from './book.model';
import { BookGenres } from './dtos/create-book.dto';

export const books: Book[] = [
  {
    name: 'Star Wars',
    likes: 10,
    email: 'start@gmai.com',
    sales: 3,
    author: 'Sarah Drasner',
    genre: [BookGenres.Action],
  },
  {
    name: 'Lad',
    author: 'hame@gmail.com',
    email: 'ade@gmail.com',
    sales: 0,
    likes: 1,
    genre: [BookGenres.Action],
  },
  {
    name: 'Galactic Odyssey',
    likes: 25,
    email: 'galactic@gmail.com',
    sales: 12,
    author: 'Alex Turner',
    genre: [BookGenres.ScienceFiction],
  },
  {
    name: 'Shadow Realm',
    likes: 8,
    email: 'shadow@gmail.com',
    sales: 5,
    author: 'Emma Thompson',
    genre: [BookGenres.Fantasy],
  },
  {
    name: 'Eternal Embrace',
    likes: 15,
    email: 'embrace@gmail.com',
    sales: 7,
    author: 'David Miller',
    genre: [BookGenres.Romance],
  },
  {
    name: 'Code Breaker',
    likes: 12,
    email: 'codebreaker@gmail.com',
    sales: 3,
    author: 'Michael Roberts',
    genre: [BookGenres.Mystery],
  },
  {
    name: 'Starlight Serenade',
    likes: 18,
    email: 'starlight@gmail.com',
    sales: 10,
    author: 'Jessica Wilson',
    genre: [BookGenres.Romance],
  },
  {
    name: 'Cyber Nexus',
    likes: 7,
    email: 'cyber@gmail.com',
    sales: 2,
    author: 'Ryan Carter',
    genre: [BookGenres.ScienceFiction],
  },
  {
    name: 'Whispers in the Wind',
    likes: 22,
    email: 'whispers@gmail.com',
    sales: 8,
    author: 'Sophie Anderson',
    genre: [BookGenres.Fantasy],
  },
  {
    name: 'Midnight Mirage',
    likes: 14,
    email: 'midnight@gmail.com',
    sales: 6,
    author: 'Daniel White',
    genre: [BookGenres.Mystery],
  },
  {
    name: 'Chronicles of Tomorrow',
    likes: 30,
    email: 'chronicles@gmail.com',
    sales: 15,
    author: 'Olivia Brown',
    genre: [BookGenres.ScienceFiction],
  },
  {
    name: 'Infernos Kiss',
    likes: 11,
    email: 'inferno@gmail.com',
    sales: 4,
    author: 'Christopher Turner',
    genre: [BookGenres.Fantasy],
  },
  {
    name: 'Silent Shadows',
    likes: 20,
    email: 'shadows@gmail.com',
    sales: 9,
    author: 'Eva Martinez',
    genre: [BookGenres.Mystery],
  },
  {
    name: 'Astral Symphony',
    likes: 28,
    email: 'astral@gmail.com',
    sales: 11,
    author: 'William Johnson',
    genre: [BookGenres.ScienceFiction],
  },
  {
    name: 'Quantum Paradox',
    likes: 9,
    email: 'quantum@gmail.com',
    sales: 3,
    author: 'Sophia Clark',
    genre: [BookGenres.ScienceFiction],
  },
  {
    name: 'Masquerade of Love',
    likes: 17,
    email: 'masquerade@gmail.com',
    sales: 7,
    author: 'Lucas Adams',
    genre: [BookGenres.Romance],
  },
  {
    name: 'Cipher Conspiracy',
    likes: 13,
    email: 'cipher@gmail.com',
    sales: 5,
    author: 'Rachel Turner',
    genre: [BookGenres.Mystery],
  },
  {
    name: 'Celestial Harmony',
    likes: 23,
    email: 'celestial@gmail.com',
    sales: 10,
    author: 'Jason Miller',
    genre: [BookGenres.Fantasy],
  },
  {
    name: 'Neon Dreams',
    likes: 6,
    email: 'neon@gmail.com',
    sales: 1,
    author: 'Lily White',
    genre: [BookGenres.ScienceFiction],
  },
  {
    name: 'Whirlwind Romance',
    likes: 19,
    email: 'whirlwind@gmail.com',
    sales: 8,
    author: 'Matthew Turner',
    genre: [BookGenres.Romance],
  },
  {
    name: "Enigma's Veil",
    likes: 16,
    email: 'enigma@gmail.com',
    sales: 6,
    author: 'Emily Davis',
    genre: [BookGenres.Mystery],
  },
  {
    name: "Orion's Legacy",
    likes: 26,
    email: 'orion@gmail.com',
    sales: 12,
    author: 'Nathan Clark',
    genre: [BookGenres.ScienceFiction],
  },
  {
    name: 'Serpentine Whispers',
    likes: 10,
    email: 'serpentine@gmail.com',
    sales: 4,
    author: 'Sophie Turner',
    genre: [BookGenres.Fantasy],
  },
  {
    name: 'Labyrinth of Love',
    likes: 21,
    email: 'labyrinth@gmail.com',
    sales: 9,
    author: 'Daniel Turner',
    genre: [BookGenres.Romance],
  },
  {
    name: 'Phantom Protocol',
    likes: 27,
    email: 'phantom@gmail.com',
    sales: 11,
    author: 'Grace Miller',
    genre: [BookGenres.Mystery],
  },
  {
    name: 'Stellar Symphony',
    likes: 7,
    email: 'stellar@gmail.com',
    sales: 2,
    author: 'James White',
    genre: [BookGenres.ScienceFiction],
  },
  {
    name: 'Ethereal Echoes',
    likes: 14,
    email: 'ethereal@gmail.com',
    sales: 5,
    author: 'Ava Turner',
    genre: [BookGenres.Fantasy],
  },
  {
    name: 'Reckless Rendezvous',
    likes: 18,
    email: 'reckless@gmail.com',
    sales: 8,
    author: 'Noah Davis',
    genre: [BookGenres.Romance],
  },
  {
    name: 'Chronicle of Shadows',
    likes: 29,
    email: 'chronicle@gmail.com',
    sales: 13,
    author: 'Isabella Turner',
    genre: [BookGenres.Mystery],
  },
  {
    name: 'Vortex of Destiny',
    likes: 12,
    email: 'vortex@gmail.com',
    sales: 4,
    author: 'Caleb Anderson',
    genre: [BookGenres.ScienceFiction],
  },
  {
    name: 'Moonlit Serenade',
    likes: 20,
    email: 'moonlit@gmail.com',
    sales: 9,
    author: 'Hannah Turner',
    genre: [BookGenres.Romance],
  },
  {
    name: 'Abyssal Enigma',
    likes: 15,
    email: 'abyssal@gmail.com',
    sales: 6,
    author: 'Leo Davis',
    genre: [BookGenres.Mystery],
  },
];
